# Análisis de Niveles
A través del siguiente notebook se va a revisar la distribución de los niveles para cada variable categórica restante para poder agrupar de forma más compacta los niveles que se tienen de momento.

In [2]:
import pandas as pd
import os

In [3]:
path = r"C:\Users\andre\OneDrive\Escritorio\Proyecto de Grado\result\db_agrupado"
mes = 'Enero'
path_csv = os.path.join(path, mes + '_Agrupado.csv')
data = pd.read_csv(path_csv, encoding='Latin1', sep=';')

In [4]:
data.head()

,DIRECTORIO,ZONA_TERRITORIAL,FACTOR_EXPANSION,DPTO,SEXO,EDAD,PARENTESCO_JEFE_DE_HOGAR,MADRE_RESIDE_HOGAR,PADRE_RESIDE_HOGAR,SE_CONSIDERA_CAMPESINO,...,TIPO_OCUPACION_VIVIENDA,HOGAR_TIENE_CUENTA_CORRIENTE,HOGAR_TIENE_CUENTA_AHORROS,HOGAR_TIENE_CDT,HOGAR_TIENE_PRESTAMO_COMPRA_VIVIENDA,HOGAR_TIENE_PRESTAMO_COMPRA_VEHICULO,HOGAR_TIENE_PRESTAMO_LIBRE_INVERSION,HOGAR_TIENE_TARJETA_CREDITO,NUMERO_PERSONAS_HOGAR,DISCAPACIDAD
0,7309060,Cabecera,1580.677273,CUNDINAMARCA,Masculino,27,"Pareja, esposo(a), conyuge, companero(a)",No,No,Si,...,En arriendo o subarriendo,No,Si,No,No,No,No,No,3,Sin discapacidad
1,7309064,Resto,324.598262,RISALRALDA,Masculino,18,"Hijo(a), hijastro(a)",Si,No,Si,...,En arriendo o subarriendo,No,Si,No,No,No,No,No,5,Sin discapacidad
2,7309067,Resto,167.457366,RISALRALDA,Femenino,25,"Hijo(a), hijastro(a)",No,Si,Si,...,"Propia, totalmente pagada",No,Si,No,No,No,No,No,2,Sin discapacidad
3,7309073,Resto,202.189536,RISALRALDA,Femenino,27,"Hijo(a), hijastro(a)",Si,No,Si,...,En usufructo,No,Si,No,No,No,No,No,6,Sin discapacidad
4,7309073,Resto,202.189536,RISALRALDA,Femenino,23,"Hijo(a), hijastro(a)",Si,No,Si,...,En usufructo,No,Si,No,No,No,No,No,6,Sin discapacidad

In [5]:
categoric_vars = data.select_dtypes(include=['object']).columns.to_list()

In [6]:
for var in categoric_vars:
    print("Variable: {}".format(var))
    print(data[var].value_counts())
    print("-"*20)

Variable: ZONA_TERRITORIAL
ZONA_TERRITORIAL
Cabecera    6146
Resto        756
Name: count, dtype: int64
--------------------
Variable: DPTO
DPTO
ANTIOQUIA             512
VALLE                 406
SANTANDER             374
RISALRALDA            365
NORTE DE SANTANDER    350
BOLIVAR               299
META                  290
ATLANTICO             277
MAGDALENA             276
HUILA                 275
CALDAS                268
QUINDIO               262
BOGOTA                260
NARINO                245
TOLIMA                225
CAUCA                 218
CAQUETA               215
BOYACA                213
SUCRE                 212
CHOCO                 208
LA GUAJIRA            204
CESAR                 193
CORDOBA               187
CUNDINAMARCA          141
SAN ANDRES            112
ARAUCA                 57
GUAVIARE               55
GUAINIA                46
CASANARE               43
VICHADA                40
PUTUMAYO               35
VAUPES                 21
AMAZONAS               18
Name: count, dtype: int64
--------------------
Variable: SEXO
SEXO
Masculino    4150
Femenino     2752
Name: count, dtype: int64
--------------------
Variable: PARENTESCO_JEFE_DE_HOGAR
PARENTESCO_JEFE_DE_HOGAR
Hijo(a), hijastro(a)                        3212
Jefe (a) del hogar                          1804
Otro pariente                                773
Pareja, esposo(a), conyuge, companero(a)     749
Hermano(a) o hermanastro(a)                  186
No pariente                                  178
Name: count, dtype: int64
--------------------
Variable: MADRE_RESIDE_HOGAR
MADRE_RESIDE_HOGAR
No           3363
Si           3299
Fallecida     240
Name: count, dtype: int64
--------------------
Variable: PADRE_RESIDE_HOGAR
PADRE_RESIDE_HOGAR
No           4498
Si           1686
Fallecido     718
Name: count, dtype: int64
--------------------
Variable: SE_CONSIDERA_CAMPESINO
SE_CONSIDERA_CAMPESINO
No            5315
Si            1570
No informa      17
Name: count, dtype: int64
--------------------
Variable: COMUNIDAD_ES_CAMPESINA
COMUNIDAD_ES_CAMPESINA
No            5759
Si            1120
No informa      23
Name: count, dtype: int64
--------------------
Variable: ETNIA
ETNIA
Ninguno de los anteriores           6161
Negro, mulato (afrodescendiente)     509
Indigena                             210
Otra etnia                            22
Name: count, dtype: int64
--------------------
Variable: ESTADO_CIVIL
ESTADO_CIVIL
Esta soltero (a)                                                4097
No esta  casado (a)  y vive en pareja   hace dos anos  o mas    1665
No esta casado(a) y vive en pareja  hace  menos de dos anos      444
Esta separado (a) o divorciado (a)                               438
Esta casado (a)                                                  245
Esta viudo (a)                                                    13
Name: count, dtype: int64
--------------------
Variable: AFILIADO_SALUD
AFILIADO_SALUD
Si                     6266
No                      623
No sabe, no informa      13
Name: count, dtype: int64
--------------------
Variable: LEER_ESCRIBIR
LEER_ESCRIBIR
Si    6868
No      34
Name: count, dtype: int64
--------------------
Variable: ACTUALMENTE_ESTUDIA
ACTUALMENTE_ESTUDIA
No    6258
Si     644
Name: count, dtype: int64
--------------------
Variable: MAYOR_NIVEL_EDUCATIVO
MAYOR_NIVEL_EDUCATIVO
Media academica (Bachillerato clasico)    2796
Universitaria                             1367
Basica secundaria (6o - 9o)                854
Tecnica profesional                        790
Basica primaria (1o - 5o)                  350
Tecnologica                                318
Media tecnica (Bachillerato tecnico)       280
Postgrado                                  101
Ninguno                                     33
Normalista                                  13
Name: count, dtype: int64
--------------------
Variable: ORIENTACION_SEXUAL
ORIENTACION_SEXUAL
Mujeres        4113
Hombres        2755
Ambos sexos      34
Name: count, dtype: int64
--------------------
Variable: GENERO
GENERO
Hombre          4145
Mujer           2749
Hombre trans       5
Mujer trans        3
Name: count, dtype: int64
--------------------
Variable: TIPO_VIVIENDA
TIPO_VIVIENDA
Casa                                                                        3506
Apartamento                                                                 3241
Cuarto (s) en inquilinato                                                    106
Cuarto (s) en otro  tipo de estructura                                        30
Vivienda indigena                                                             17
Otra vivienda (carpa,  vagon, embarcacion, cueva, refugio natural, etc.)       2
Name: count, dtype: int64
--------------------
Variable: SERVICIOS_ENERGIA_ELECTRICA
SERVICIOS_ENERGIA_ELECTRICA
Si    6876
No      26
Name: count, dtype: int64
--------------------
Variable: ESTRATO_ENERGIA_ELECTRICA
ESTRATO_ENERGIA_ELECTRICA
Bajo - Bajo                              2808
Bajo                                     2333
Medio - Bajo                             1103
Medio                                     300
Conexion Pirata                           150
Medio - Alto                               96
No sabe o cuenta con Planta Electrica      63
No tiene servicio electrico                26
Alto                                       23
Name: count, dtype: int64
--------------------
Variable: SERVICIOS_GAS_NATURAL
SERVICIOS_GAS_NATURAL
Si    4917
No    1985
Name: count, dtype: int64
--------------------
Variable: SERVICIOS_ALCANTARILLADO
SERVICIOS_ALCANTARILLADO
Si    5674
No    1228
Name: count, dtype: int64
--------------------
Variable: SERVICIOS_RECOLECCION_BASURAS
SERVICIOS_RECOLECCION_BASURAS
Si    6417
No     485
Name: count, dtype: int64
--------------------
Variable: SERVICIOS_ACUEDUCTO
SERVICIOS_ACUEDUCTO
Si    6377
No     525
Name: count, dtype: int64
--------------------
Variable: TIPO_SANITARIO
TIPO_SANITARIO
Inodoro conectado a alcantarillado    5642
Inodoro conectado a pozo septico       909
Inodoro sin conexion                   209
No tiene servicio sanitario            106
Bajamar                                 28
Letrina                                  8
Name: count, dtype: int64
--------------------
Variable: COMO_ELIMINA_BASURA
COMO_ELIMINA_BASURA
Por recoleccion publica o privada             6401
La queman o entierran                          337
La tiran a un patio, lote, zanja o baldio       86
La eliminan de otra forma                       57
La tiran a un rio, quebrada, cano o laguna      21
Name: count, dtype: int64
--------------------
Variable: DONDE_OBTIENE_AGUA
DONDE_OBTIENE_AGUA
De acueducto por tuberia                       6075
Agua embotellada o en bolsa                     234
De otra fuente por tuberia                      176
Aguas lluvias                                   147
De pozo con bomba                               141
Rio, quebrada, nacimiento o manantial            62
De pozo sin bomba, aljibe, jaguey o barreno      31
Carrotanque                                      18
Aguatero                                         11
De pila publica                                   7
Name: count, dtype: int64
--------------------
Variable: DONDE_PREPARA_ALIMENTOS
DONDE_PREPARA_ALIMENTOS
En un cuarto usado solo para cocinar?              5651
En una sala comedor con lavaplatos?                 786
En una sala comedor sin lavaplatos?                 142
En un patio, corredor, enramada, al aire libre?     137
En un cuarto usado tambien para dormir?             121
En ninguna parte, no preparan alimentos?             65
Name: count, dtype: int64
--------------------
Variable: TIPO_OCUPACION_VIVIENDA
TIPO_OCUPACION_VIVIENDA
En arriendo o subarriendo    3566
Propia, totalmente pagada    1706
En usufructo                  996
Posesion sin titulo           298
Propia, la estan pagando      160
Propiedad colectiva           151
Otra                           25
Name: count, dtype: int64
--------------------
Variable: HOGAR_TIENE_CUENTA_CORRIENTE
HOGAR_TIENE_CUENTA_CORRIENTE
No    6832
Si      70
Name: count, dtype: int64
--------------------
Variable: HOGAR_TIENE_CUENTA_AHORROS
HOGAR_TIENE_CUENTA_AHORROS
Si    4269
No    2633
Name: count, dtype: int64
--------------------
Variable: HOGAR_TIENE_CDT
HOGAR_TIENE_CDT
No    6889
Si      13
Name: count, dtype: int64
--------------------
Variable: HOGAR_TIENE_PRESTAMO_COMPRA_VIVIENDA
HOGAR_TIENE_PRESTAMO_COMPRA_VIVIENDA
No    6793
Si     109
Name: count, dtype: int64
--------------------
Variable: HOGAR_TIENE_PRESTAMO_COMPRA_VEHICULO
HOGAR_TIENE_PRESTAMO_COMPRA_VEHICULO
No    6849
Si      53
Name: count, dtype: int64
--------------------
Variable: HOGAR_TIENE_PRESTAMO_LIBRE_INVERSION
HOGAR_TIENE_PRESTAMO_LIBRE_INVERSION
No    6548
Si     354
Name: count, dtype: int64
--------------------
Variable: HOGAR_TIENE_TARJETA_CREDITO
HOGAR_TIENE_TARJETA_CREDITO
No    6337
Si     565
Name: count, dtype: int64
--------------------
Variable: DISCAPACIDAD
DISCAPACIDAD
Sin discapacidad         6516
Discapacidad leve         373
Discapacidad moderada       9
Discapacidad grave          4
Name: count, dtype: int64
--------------------

De acuerdo a lo anterior, me quedo con las siguientes conclusiones:
- En la sección de género voy a combinar los níveles de hombre trans y mujer trans por el único nivel de persona trans
- Estoy en ciertas variables como, el tipo de sanitario que se teiene en la vivienda o la forma que se recolecta el agua, es posible agrupar los niveles que tienen una frecuencia muy baja dentro de la categoría, otros
- Debo hablar con el profe Mario para saber que puedo hacer en aquellas variables que contienen el nivel "No sabe, no informa"
- Debo observar otra forma de agrupar a la discapacidad, ya que según el método actual no seré capaz de tener una distribución adecuada de los datos, de hecho, dada su naturaleza donde el 95% de los datos están asociados a un solo nivel, sería adecuado evaluar su relevancia sobre la variable objetivo, esto se puede realizar a través de un análisis por medio de un IV.